/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"
#include "position.h"
#include "amazons.h"
#include "board.h"



/* Prototypes */

/* Globals */
Board *board;
GtkWidget *main_window;


int main (int argc, char *argv[])
{
  GtkWidget *GamazonsMain;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  GamazonsMain = create_GamazonsMain ();
  main_window = GamazonsMain;
  init_game_board(GamazonsMain);
  gtk_widget_show (GamazonsMain);
  init_engine();

  gtk_main ();
  return 0;
}




